### PR TITLE
debug-ui-v1

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/165)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 26 of 28 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/165)* status: all files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[src/index.js, line 22 at r3](https://reviewable.io/reviews/kube-hpc/simulator/165#-MdGScey8r5M4IABgREY:-MdGScey8r5M4IABgREZ:byh9gxa) ([raw file](https://github.com/kube-hpc/simulator/blob/0272cc9e540799027ffe1efefefc1b0336000103/src/index.js#L22)):*
> ```JavaScript
>   }, [dispatch]);
> 
>   const { hasConfig } = useSelector(selectors.config);
> ```

What about debugging after the pipeline has completed? (like `run cache`)
___
*[src/reducers/algorithm.reducer.js, line 72 at r3](https://reviewable.io/reviews/kube-hpc/simulator/165#-MdGSRHs2o5FjNDbQEei:-MdGSRHs2o5FjNDbQEej:b9fgxx3) ([raw file](https://github.com/kube-hpc/simulator/blob/0272cc9e540799027ffe1efefefc1b0336000103/src/reducers/algorithm.reducer.js#L72)):*
> ```JavaScript
>       baseSelectors.selectById(state.algorithms.collection, id),
>     /** @param {State} state */
>     count: state =>
> ```

I noticed that if I stop pipeline, I can't see the `Algorithm Details` anymore

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/165)* status: all files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[src/index.js, line 22 at r3](https://reviewable.io/reviews/kube-hpc/simulator/165#-MdGScey8r5M4IABgREY:-MdGTVt_AwgqUQeW2N5O:bbe0e2s) ([raw file](https://github.com/kube-hpc/simulator/blob/0272cc9e540799027ffe1efefefc1b0336000103/src/index.js#L22)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

What about debugging after the pipeline has completed? (like `run cache`)
</blockquote></details>

That's why I called the brach debug-ui-v1. There will be v2 :-)
___
*[src/reducers/algorithm.reducer.js, line 72 at r3](https://reviewable.io/reviews/kube-hpc/simulator/165#-MdGSRHs2o5FjNDbQEei:-MdGTGXCDNLoQp8Z6Ruw:b7nh86m) ([raw file](https://github.com/kube-hpc/simulator/blob/0272cc9e540799027ffe1efefefc1b0336000103/src/reducers/algorithm.reducer.js#L72)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

I noticed that if I stop pipeline, I can't see the `Algorithm Details` anymore
</blockquote></details>

That's because the debug algorithm is deleted when the pipeline finishes. I talked to Golan yesterday about it. We need to think of a different way to do it

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/165)* status: all files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[src/index.js, line 22 at r3](https://reviewable.io/reviews/kube-hpc/simulator/165#-MdGScey8r5M4IABgREY:-MdGTcZW2cO8UsZyKf-J:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/0272cc9e540799027ffe1efefefc1b0336000103/src/index.js#L22)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

That's why I called the brach debug-ui-v1. There will be v2 :-)
</blockquote></details>

Done.
___
*[src/reducers/algorithm.reducer.js, line 72 at r3](https://reviewable.io/reviews/kube-hpc/simulator/165#-MdGSRHs2o5FjNDbQEei:-MdGTd4FDWdYj8aYTVVp:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/0272cc9e540799027ffe1efefefc1b0336000103/src/reducers/algorithm.reducer.js#L72)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

That's because the debug algorithm is deleted when the pipeline finishes. I talked to Golan yesterday about it. We need to think of a different way to do it
</blockquote></details>

Done.

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/165)* status: all files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[src/index.js, line 22 at r3](https://reviewable.io/reviews/kube-hpc/simulator/165#-MdGScey8r5M4IABgREY:-MdGVwr1As4XN_pKftIK:bcdhhtp) ([raw file](https://github.com/kube-hpc/simulator/blob/0272cc9e540799027ffe1efefefc1b0336000103/src/index.js#L22)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What is the point?

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/165#-:-MdGeRFe0mJ8X-l5vxF1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Pull request merged**
