### PR TITLE
add logMode to settings, and log rest call

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/140)

### CODE REVIEW

**Review by reggev — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/140)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @yehiyam)

___
*[src/config/template/log-mode.template.js, line 3 at r1](https://reviewable.io/reviews/kube-hpc/simulator/140#-MTV49FA4lZXILsjvIL6:-MTV49FA4lZXILsjvIL7:bpquk3m) ([raw file](https://github.com/kube-hpc/simulator/blob/d42223dbae0f67368435e06c44b6d0d6091e587b/src/config/template/log-mode.template.js#L3)):*
> ```JavaScript
> import { logModes } from '@hkube/consts';
> 
> export const logModeTypes = {
> ```

Why do we need this template file? 
it's not re-usable and has no real reason to be outside of the component that renders the actual input
It makes understanding the actual output of the component obscured
___
*[src/Routes/Base/Header/Settings/LogMode.react.js, line 12 at r1](https://reviewable.io/reviews/kube-hpc/simulator/140#-MTV6B_88yJR2GKMosOI:-MTV6B_88yJR2GKMosOJ:brr1uzb) ([raw file](https://github.com/kube-hpc/simulator/blob/d42223dbae0f67368435e06c44b6d0d6091e587b/src/Routes/Base/Header/Settings/LogMode.react.js#L12)):*
> ```JavaScript
>   const onChange = useCallback(
>     // eslint-disable-next-line
>     ({ target: { value: logMode } }) => setSettings({ logMode }),
> ```

logMode is already declared above, rename one of the instances
___
*[src/Routes/Base/Header/Settings/LogMode.react.js, line 19 at r1](https://reviewable.io/reviews/kube-hpc/simulator/140#-MTV4Xt2C3zbkedwvvA3:-MTV4Xt2C3zbkedwvvA4:b-hpxguy) ([raw file](https://github.com/kube-hpc/simulator/blob/d42223dbae0f67368435e06c44b6d0d6091e587b/src/Routes/Base/Header/Settings/LogMode.react.js#L19)):*
> ```JavaScript
>       <Typography.Text strong>Log Mode</Typography.Text>
>       <Radio.Group value={logMode} onChange={onChange}>
>         {Object.entries(logModeTypes).map(([key, value]) => (
> ```

The keys may collide with other keys - when using non-globally unique keys it's better to scope them ex: `my-scope-${key}`.

I wouldn't render this as a loop I would just put the actual values - React is declarative you can use JSX "like a config file".

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/140)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @reggev)

___
*[src/config/template/log-mode.template.js, line 3 at r1](https://reviewable.io/reviews/kube-hpc/simulator/140#-MTV49FA4lZXILsjvIL6:-MTVAFSlE9sZhYNz63Jd:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/d42223dbae0f67368435e06c44b6d0d6091e587b/src/config/template/log-mode.template.js#L3)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

Why do we need this template file? 
it's not re-usable and has no real reason to be outside of the component that renders the actual input
It makes understanding the actual output of the component obscured
</blockquote></details>

Done.
___
*[src/Routes/Base/Header/Settings/LogMode.react.js, line 12 at r1](https://reviewable.io/reviews/kube-hpc/simulator/140#-MTV6B_88yJR2GKMosOI:-MTVEVpsEPqUn8PE3iP9:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/d42223dbae0f67368435e06c44b6d0d6091e587b/src/Routes/Base/Header/Settings/LogMode.react.js#L12)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

logMode is already declared above, rename one of the instances
</blockquote></details>

Done.
___
*[src/Routes/Base/Header/Settings/LogMode.react.js, line 19 at r1](https://reviewable.io/reviews/kube-hpc/simulator/140#-MTV4Xt2C3zbkedwvvA3:-MTVEX1J0Uh_yDri6ORP:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/d42223dbae0f67368435e06c44b6d0d6091e587b/src/Routes/Base/Header/Settings/LogMode.react.js#L19)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

The keys may collide with other keys - when using non-globally unique keys it's better to scope them ex: `my-scope-${key}`.

I wouldn't render this as a loop I would just put the actual values - React is declarative you can use JSX "like a config file".
</blockquote></details>

Done.

**Review by reggev — APPROVED** [review]
> Reviewed 3 of 8 files at r1, 1 of 1 files at r2, 1 of 2 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/140)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
