### PR TITLE
Fix all bug antd4

### PR DESCRIPTION
**Pull request by zivglik**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/190)

### CODE REVIEW

**Comment by maty21** [comment]
___
*[src/Routes/SidebarRight/AddPipeline/Steps/Nodes/InputParseJson/useInputField.js, line 10 at r7](https://reviewable.io/reviews/kube-hpc/simulator/190#-MwuKF7K2bU_7BaAmJ0M:-MwuKF7K2bU_7BaAmJ0N:b7re1jt) ([raw file](https://github.com/kube-hpc/simulator/blob/5ce2562c70346d6c1dd99cad9df1ad7cc2af1c2d/src/Routes/SidebarRight/AddPipeline/Steps/Nodes/InputParseJson/useInputField.js#L10)):*
> ```JavaScript
> 
>   const checkInputObject = (input, words) => {
>     if (input !== null && input !== undefined) {
> ```

null should cover undefined also

**Review by zivglik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/190)* status: 34 of 37 files reviewed, 2 unresolved discussions (waiting on @maty21)

___
*[src/Routes/SidebarRight/AddPipeline/Steps/Nodes/InputParseJson/index.js, line 16 at r7](https://reviewable.io/reviews/kube-hpc/simulator/190#-MwuJmCe2NDYlOkWEwQx:-MwuS6L86U7wNzr1mLnY:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/5ce2562c70346d6c1dd99cad9df1ad7cc2af1c2d/src/Routes/SidebarRight/AddPipeline/Steps/Nodes/InputParseJson/index.js#L16)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

didn't understand the complicated if its seems like there are duplicates

    (isRequired && inputValues === undefined) ||
    (isRequired &&
      inputValues !== undefined &&
      (inputValues[0] === '' || inputValues[0] === undefined)) ? (

</blockquote></details>

Done.
___
*[src/Routes/SidebarRight/AddPipeline/Steps/Nodes/InputParseJson/useInputField.js, line 10 at r7](https://reviewable.io/reviews/kube-hpc/simulator/190#-MwuKF7K2bU_7BaAmJ0M:-MwuTRNb5ufSaWYYpcCW:b-75nudo) ([raw file](https://github.com/kube-hpc/simulator/blob/5ce2562c70346d6c1dd99cad9df1ad7cc2af1c2d/src/Routes/SidebarRight/AddPipeline/Steps/Nodes/InputParseJson/useInputField.js#L10)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

null should cover undefined also
</blockquote></details>

It throws an error in case it is undefined , So I put it  -->  input !== undefined

**Comment by maty21** [comment]
___
*[src/Routes/SidebarRight/AddPipeline/Steps/Nodes/InputParseJson/index.js, line 16 at r7](https://reviewable.io/reviews/kube-hpc/simulator/190#-MwuJmCe2NDYlOkWEwQx:-MwzSbzy3F0NYQyVK-2Y:b2y0ws1) ([raw file](https://github.com/kube-hpc/simulator/blob/5ce2562c70346d6c1dd99cad9df1ad7cc2af1c2d/src/Routes/SidebarRight/AddPipeline/Steps/Nodes/InputParseJson/index.js#L16)):*
<details><summary><i>Previously, zivglik wrote…</i></summary><blockquote>

Done.
</blockquote></details>

inputValues&&!inputValues[0] not working ?

**Review by maty21 — DISMISSED** [review]
> Reviewed 2 of 3 files at r8, 4 of 4 files at r9, 2 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/190)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zivglik)

**Review by maty21 — APPROVED** [review]
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/190)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zivglik)

**Review by maty21 — DISMISSED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/190#-:-MwzZHSJ61AzKK6DtR4b:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zivglik)

**Review by maty21 — APPROVED** [review]
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/190)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zivglik)

**Pull request merged**
