### PR TITLE
add original flow input

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/137)

### CODE REVIEW

**Review by reggev — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/137)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @yehiyam)

___
*[src/components/common/Json/JsonSwitch/JsonSwitch.react.js, line 59 at r3](https://reviewable.io/reviews/kube-hpc/simulator/137#-MSwQ6Ij5Wc1np4CiFvw:-MSwQ6Ij5Wc1np4CiFvx:b-71xmzj) ([raw file](https://github.com/kube-hpc/simulator/blob/653b3b2ed4f71e1c7a396da5e1f62e24cd00ef5d/src/components/common/Json/JsonSwitch/JsonSwitch.react.js#L59)):*
> ```JavaScript
>   // eslint-disable-next-line
>   options: PropTypes.object,
>   // eslint-disable-next-line
> ```

If you don't want to detail the props you can just wrap the whole block with:
 /* eslint-disable react/forbid-prop-types */
// ignored props
  /* eslint-enable react/forbid-prop-types */
If you can, try to detail as mush as you can, it helps catching errors.
___
*[src/components/common/Json/JsonSwitch/JsonSwitch.react.js, line 60 at r3](https://reviewable.io/reviews/kube-hpc/simulator/137#-MSwPqUt2nHTbXj-iD8V:-MSwPqUt2nHTbXj-iD8W:bno8r9r) ([raw file](https://github.com/kube-hpc/simulator/blob/653b3b2ed4f71e1c7a396da5e1f62e24cd00ef5d/src/components/common/Json/JsonSwitch/JsonSwitch.react.js#L60)):*
> ```JavaScript
>   options: PropTypes.object,
>   // eslint-disable-next-line
>   jobId: PropTypes.string,
> ```

can you provide some default value or pull it to null if nothing is provided?
if it's required then mark it as required
___
*[src/components/common/Json/JsonTable/JsonTable.react.js, line 47 at r3](https://reviewable.io/reviews/kube-hpc/simulator/137#-MSwSIfg4XDBKOifX_ni:-MSwSIfg4XDBKOifX_nj:bc0l2rm) ([raw file](https://github.com/kube-hpc/simulator/blob/653b3b2ed4f71e1c7a396da5e1f62e24cd00ef5d/src/components/common/Json/JsonTable/JsonTable.react.js#L47)):*
> ```JavaScript
>         <>
>           <Button onClick={handleDownload}>Download</Button>
>           <a
> ```

Iv'e implemented a file called DownloadLink.js on a branch 'bugfix-datasources', that does this whole process of creating a link and clicking it whenever the href prop changes
It'll be better if you use that, I'm trying to get rid of all the uses of the socket's URL (or any other URL constructing method) inside the components...
___
*[src/components/common/Json/JsonTable/JsonTable.react.js, line 93 at r3](https://reviewable.io/reviews/kube-hpc/simulator/137#-MSwT-jmAvmE2XpobekF:-MSwT-jn3peO-jR1uWVB:b1xusa4) ([raw file](https://github.com/kube-hpc/simulator/blob/653b3b2ed4f71e1c7a396da5e1f62e24cd00ef5d/src/components/common/Json/JsonTable/JsonTable.react.js#L93)):*
> ```JavaScript
>   isMargin: PropTypes.bool,
>   key: PropTypes.oneOf([PropTypes.string, PropTypes.number]),
>   jobId: PropTypes.string,
> ```

Is it a required property?
___
*[src/hooks/usePipeline.js, line 28 at r3](https://reviewable.io/reviews/kube-hpc/simulator/137#-MSwT_I-7_gLAUoeJOGr:-MSwT_I0ATXpoY_t0vNy:bh07g4y) ([raw file](https://github.com/kube-hpc/simulator/blob/653b3b2ed4f71e1c7a396da5e1f62e24cd00ef5d/src/hooks/usePipeline.js#L28)):*
> ```JavaScript
>     [updateStored]
>   );
>   const rerunRawPipeline = async (pipeline, jobId) => {
> ```

consider wrapping this in a useCallback

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/137)* status: 0 of 6 files reviewed, 5 unresolved discussions (waiting on @reggev)

___
*[src/components/common/Json/JsonSwitch/JsonSwitch.react.js, line 59 at r3](https://reviewable.io/reviews/kube-hpc/simulator/137#-MSwQ6Ij5Wc1np4CiFvw:-MSwfBg14VpxfPgsZqQ-:bw7ci5z) ([raw file](https://github.com/kube-hpc/simulator/blob/653b3b2ed4f71e1c7a396da5e1f62e24cd00ef5d/src/components/common/Json/JsonSwitch/JsonSwitch.react.js#L59)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

If you don't want to detail the props you can just wrap the whole block with:
 /* eslint-disable react/forbid-prop-types */
// ignored props
  /* eslint-enable react/forbid-prop-types */
If you can, try to detail as mush as you can, it helps catching errors.
</blockquote></details>

added more detail
___
*[src/components/common/Json/JsonSwitch/JsonSwitch.react.js, line 60 at r3](https://reviewable.io/reviews/kube-hpc/simulator/137#-MSwPqUt2nHTbXj-iD8V:-MSwfI601W4PPUqsOxCX:b6stxm6) ([raw file](https://github.com/kube-hpc/simulator/blob/653b3b2ed4f71e1c7a396da5e1f62e24cd00ef5d/src/components/common/Json/JsonSwitch/JsonSwitch.react.js#L60)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

can you provide some default value or pull it to null if nothing is provided?
if it's required then mark it as required
</blockquote></details>

made it required
___
*[src/components/common/Json/JsonTable/JsonTable.react.js, line 47 at r3](https://reviewable.io/reviews/kube-hpc/simulator/137#-MSwSIfg4XDBKOifX_ni:-MSwfLms64JOYXOgGpXC:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/653b3b2ed4f71e1c7a396da5e1f62e24cd00ef5d/src/components/common/Json/JsonTable/JsonTable.react.js#L47)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

Iv'e implemented a file called DownloadLink.js on a branch 'bugfix-datasources', that does this whole process of creating a link and clicking it whenever the href prop changes
It'll be better if you use that, I'm trying to get rid of all the uses of the socket's URL (or any other URL constructing method) inside the components...
</blockquote></details>

Done.
___
*[src/components/common/Json/JsonTable/JsonTable.react.js, line 93 at r3](https://reviewable.io/reviews/kube-hpc/simulator/137#-MSwT-jmAvmE2XpobekF:-MSwh2Gp-rdiw5PwSBuh:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/653b3b2ed4f71e1c7a396da5e1f62e24cd00ef5d/src/components/common/Json/JsonTable/JsonTable.react.js#L93)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

Is it a required property?
</blockquote></details>

Done.
___
*[src/hooks/usePipeline.js, line 28 at r3](https://reviewable.io/reviews/kube-hpc/simulator/137#-MSwT_I-7_gLAUoeJOGr:-MSwjSFXCWXgtGGAfJmr:bgqw9t9) ([raw file](https://github.com/kube-hpc/simulator/blob/653b3b2ed4f71e1c7a396da5e1f62e24cd00ef5d/src/hooks/usePipeline.js#L28)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

consider wrapping this in a useCallback
</blockquote></details>

not sure how can I use useCallback here

**Review by reggev — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/137)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[src/hooks/usePipeline.js, line 28 at r3](https://reviewable.io/reviews/kube-hpc/simulator/137#-MSwT_I-7_gLAUoeJOGr:-MSwyUGHB_gm0XokVJu1:b-7r4z6c) ([raw file](https://github.com/kube-hpc/simulator/blob/653b3b2ed4f71e1c7a396da5e1f62e24cd00ef5d/src/hooks/usePipeline.js#L28)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

not sure how can I use useCallback here
</blockquote></details>

I added for you

**Review by reggev — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/137#-:-MSx844L3h_hTbNuoUMe:bnfp4nl)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @yehiyam)

**Pull request merged**
