### PR TITLE
use new pipelineStats format

### PR DESCRIPTION
**Pull request by yehiyam**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/150)

### CODE REVIEW

**Review by reggev — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/150)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[src/Routes/Tables/Pipelines/PipelineStats.react.js, line 23 at r1](https://reviewable.io/reviews/kube-hpc/simulator/150#-MXbDT7D1OrUkPXEwFuX:-MXbDT7D1OrUkPXEwFuY:b79nutj) ([raw file](https://github.com/kube-hpc/simulator/blob/0cb09056185402363333ed817e472d7eac1e2938/src/Routes/Tables/Pipelines/PipelineStats.react.js#L23)):*
> ```JavaScript
>         .find(s => s.name === name)
>         ?.stats?.slice()
>         .sort((a, b) => {
> ```

We have lodash installed you can use sortBy instead of slice and sort
https://lodash.com/docs/4.17.15#sortBy

**Review by yehiyam — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/150)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @reggev)

___
*[src/Routes/Tables/Pipelines/PipelineStats.react.js, line 23 at r1](https://reviewable.io/reviews/kube-hpc/simulator/150#-MXbDT7D1OrUkPXEwFuX:-MXbKt372DQiMEhxRolI:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/0cb09056185402363333ed817e472d7eac1e2938/src/Routes/Tables/Pipelines/PipelineStats.react.js#L23)):*
<details><summary><i>Previously, reggev wrote…</i></summary><blockquote>

We have lodash installed you can use sortBy instead of slice and sort
https://lodash.com/docs/4.17.15#sortBy
</blockquote></details>

Done.

**Review by reggev — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/150)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[src/Routes/Tables/Pipelines/PipelineStats.react.js, line 21 at r3](https://reviewable.io/reviews/kube-hpc/simulator/150#-MXbPrcv4W3u9AtvSaY8:-MXbPrcw2r1FVg350-yb:b-2xbp6n) ([raw file](https://github.com/kube-hpc/simulator/blob/049de921d47b2fbc8d37f0307e0385410d46372e/src/Routes/Tables/Pipelines/PipelineStats.react.js#L21)):*
> ```JavaScript
>     () =>
>       [].concat(
>         ...[
> ```

are you sure you need to deconstruct before concatenating?
and why not just
 ([] || dataStats).filter().map()
of even:
dataStats?.filter().map ?? []

**Review by reggev — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/150)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yehiyam)

**Pull request merged**
