### PR TITLE
Algorithm cache params

### PR DESCRIPTION
**Pull request by reggev**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/111)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/111)* status: all files reviewed, 2 unresolved discussions (waiting on @maty21 and @reggev)

___
*[src/components/Sidebar/SidebarRight/AddAlgorithm/AddAlgorithmForm.react.js, line 60 at r1](https://reviewable.io/reviews/kube-hpc/simulator/111#-MIoHTv53Efs8hPFi4c9:-MIoHTv53Efs8hPFi4cA:b-5p4wke) ([raw file](https://github.com/kube-hpc/simulator/blob/6cf557b1a526ecfa02224a36dd6a2cdb37a63725/src/components/Sidebar/SidebarRight/AddAlgorithm/AddAlgorithmForm.react.js#L60)):*
> ```
> // eslint-disable-next-line
> ```
Remove all the /* eslint-disable */
___
*[src/components/Sidebar/SidebarRight/AddAlgorithm/AddAlgorithmForm.react.js, line 112 at r1](https://reviewable.io/reviews/kube-hpc/simulator/111#-MIoHiXyAuFEu8hqAkah:-MIoHiXyAuFEu8hqAkai:b-dczzvy) ([raw file](https://github.com/kube-hpc/simulator/blob/6cf557b1a526ecfa02224a36dd6a2cdb37a63725/src/components/Sidebar/SidebarRight/AddAlgorithm/AddAlgorithmForm.react.js#L112)):*
> ```JavaScript
>       const { env, entryPoint, baseImage, ...rest } = formObject[buildType];
> 
>       // NOTE: this is a workaround, the component sometimes submits units only when no number is provided
> ```

I can't put the value 0, it set default value 0f 1

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/111)* status: all files reviewed, 3 unresolved discussions (waiting on @maty21 and @reggev)

___
*[src/components/Sidebar/SidebarRight/AddAlgorithm/AddAlgorithmForm.react.js, line 58 at r1](https://reviewable.io/reviews/kube-hpc/simulator/111#-MIoNc8a06Cr-LjIFWGo:-MIoNc8a06Cr-LjIFWGp:bd30jxb) ([raw file](https://github.com/kube-hpc/simulator/blob/6cf557b1a526ecfa02224a36dd6a2cdb37a63725/src/components/Sidebar/SidebarRight/AddAlgorithm/AddAlgorithmForm.react.js#L58)):*
> ```JavaScript
> const getBuildTypes = ({ buildType, ...props }) => {
>   const { CODE, IMAGE, GIT } = BUILD_TYPES;
>   const isRequired = type => type === buildType;
> ```

I will also consider adding tooltips.

**Review by yehiyam — COMMENTED** [review]
I think it is better to leave it empty by default, and also collapse the whole "advanced" section. Leaving it empty will use the default set when installing hkube
@maty21 @nassiharel What do you think?

> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/111#-:-MIrdyo2Ejnobjw7mjK9:b-ch6rep)* status: all files reviewed, 3 unresolved discussions (waiting on @maty21 and @reggev)

**Comment by reggev** [comment]
> I think it is better to leave it empty by default, and also collapse the whole "advanced" section. Leaving it empty will use the default set when installing hkube
> @maty21 @NassiHarel What do you think?
> 
> > _[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/111#-:-MIrdyo2Ejnobjw7mjK9:b-ch6rep)_ status: all files reviewed, 3 unresolved discussions (waiting on @maty21 and @reggev)

I think showing the user the default value instead of empty=" some unknown/hidden default" is a better alternative.
As for collapsing the advanced section, for now, I don't see any added benefit for it.
I do think we need the tooltips @NassiHarel suggested.

**Comment by reggev** [comment]
> > Reviewed 5 of 5 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/111)_ status: all files reviewed, 2 unresolved discussions (waiting on @maty21 and @reggev)
> 
> _[src/components/Sidebar/SidebarRight/AddAlgorithm/AddAlgorithmForm.react.js, line 60 at r1](https://reviewable.io/reviews/kube-hpc/simulator/111#-MIoHTv53Efs8hPFi4c9:-MIoHTv53Efs8hPFi4cA:b-5p4wke) ([raw file](https://github.com/kube-hpc/simulator/blob/6cf557b1a526ecfa02224a36dd6a2cdb37a63725/src/components/Sidebar/SidebarRight/AddAlgorithm/AddAlgorithmForm.react.js#L60)):_
> 
> > ```
> > // eslint-disable-next-line
> > ```
> 
> Remove all the /* eslint-disable */
> 
> _[src/components/Sidebar/SidebarRight/AddAlgorithm/AddAlgorithmForm.react.js, line 112 at r1](https://reviewable.io/reviews/kube-hpc/simulator/111#-MIoHiXyAuFEu8hqAkah:-MIoHiXyAuFEu8hqAkai:b-dczzvy) ([raw file](https://github.com/kube-hpc/simulator/blob/6cf557b1a526ecfa02224a36dd6a2cdb37a63725/src/components/Sidebar/SidebarRight/AddAlgorithm/AddAlgorithmForm.react.js#L112)):_
> 
> > ```js
> >       const { env, entryPoint, baseImage, ...rest } = formObject[buildType];
> > 
> >       // NOTE: this is a workaround, the component sometimes submits units only when no number is provided
> > ```
> 
> I can't put the value 0, it set default value 0f 1

Most of the issues eslint was notifying are resolved on the convert_to_router branch and will be merged with that branch. 
I tagged them with TODO for any case I missed something, so it'll be easier to track and fix.
As for setting the value to 0, I'll resolve it and push an update.

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/111#-:-MItHJ4lCBYqzSeUiZVb:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @maty21, @NassiHarel, and @reggev)

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/111#-:-MIySiOF72bzK_aLOlMG:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @maty21, @NassiHarel, and @reggev)

**Pull request merged**
