### PR TITLE
feat: streaming metrics

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/136)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/136)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[src/utils/graph.js, line 136 at r2](https://reviewable.io/reviews/kube-hpc/simulator/136#-MSfwphT9QHwTWYRtjcx:-MSfwphT9QHwTWYRtjcy:boappdv) ([raw file](https://github.com/kube-hpc/simulator/blob/aede6e2b0946840974b7f032bc687a6b208686c2/src/utils/graph.js#L136)):*
> ```JavaScript
>   };
>   let styles;
>   if (metrics) {
> ```

how can `metrics` be null?

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/136)* status: all files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[src/utils/graph.js, line 136 at r2](https://reviewable.io/reviews/kube-hpc/simulator/136#-MSfwphT9QHwTWYRtjcx:-MSfxUE80Nlvpl3ZXt_X:bgsdl4n) ([raw file](https://github.com/kube-hpc/simulator/blob/aede6e2b0946840974b7f032bc687a6b208686c2/src/utils/graph.js#L136)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

how can `metrics` be null?
</blockquote></details>

1. batch pipeline
2. stream pipeline, on start

**Review by yehiyam — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/136)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
