### PR TITLE
feat: add storage usage

### PR DESCRIPTION
**Pull request by NassiHarel**
Add minimal disk usage view, maybe @reggev will make it nicer

---
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/109)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/109)* status: all files reviewed, 5 unresolved discussions (waiting on @NassiHarel and @reggev)

___
*[src/components/Sidebar/SidebarRight/Content.react.js, line 62 at r1](https://reviewable.io/reviews/kube-hpc/simulator/109#-MHABXGuByGYB2uPibE6:-MHABXGv2VILkbBdMyr2:b3zumop) ([raw file](https://github.com/kube-hpc/simulator/blob/50ff7029efe6962c8b18d2c6a44242f1a3f83268/src/components/Sidebar/SidebarRight/Content.react.js#L62)):*
> ```JavaScript
>   [RIGHT_SIDEBAR_NAMES.DISK]: {
>     width: DRAWER_SIZE.DISK,
>     title: 'Cluster DISK Usage',
> ```

I think `Hkube Storage Usage` is more appropriate
___
*[src/components/Sidebar/SidebarRight/DiskSpace/DiskSpace.react.js, line 20 at r1](https://reviewable.io/reviews/kube-hpc/simulator/109#-MHACFSt4vs_ox3d6P1l:-MHACFSt4vs_ox3d6P1m:b-j380qt) ([raw file](https://github.com/kube-hpc/simulator/blob/50ff7029efe6962c8b18d2c6a44242f1a3f83268/src/components/Sidebar/SidebarRight/DiskSpace/DiskSpace.react.js#L20)):*
> ```JavaScript
>       label: `free ${freeH}`,
>       value: free,
>       color: 'hsl(357, 70%, 50%)',
> ```

I think Dennis put the colors in 'styles/colors'
___
*[src/components/Sidebar/SidebarRight/DiskSpace/DiskSpace.react.js, line 50 at r1](https://reviewable.io/reviews/kube-hpc/simulator/109#-MHACUr98LvdupVo3PCa:-MHACUr98LvdupVo3PCb:bg73shu) ([raw file](https://github.com/kube-hpc/simulator/blob/50ff7029efe6962c8b18d2c6a44242f1a3f83268/src/components/Sidebar/SidebarRight/DiskSpace/DiskSpace.react.js#L50)):*
> ```JavaScript
>   const data = adaptedData({ free, used, freeH, usedH, usedP, freeP });
> 
>   if (freeP < 20) {
> ```

Put a red/orange dot on the storage usage icon, like on the CPU and MEM
___
*[src/components/Sidebar/SidebarRight/DiskSpace/DiskSpace.react.js, line 81 at r1](https://reviewable.io/reviews/kube-hpc/simulator/109#-MHACf3Y4ilTQQPda2FA:-MHACf3Y4ilTQQPda2FB:blvuh30) ([raw file](https://github.com/kube-hpc/simulator/blob/50ff7029efe6962c8b18d2c6a44242f1a3f83268/src/components/Sidebar/SidebarRight/DiskSpace/DiskSpace.react.js#L81)):*
> ```JavaScript
>         radialLabelsLinkColor={{ from: 'color' }}
>         slicesLabelsSkipAngle={10}
>         slicesLabelsTextColor="#333333"
> ```

Same as above. Put all colors in one place
___
*[src/reducers/diskSpace.reducer.js, line 9 at r1](https://reviewable.io/reviews/kube-hpc/simulator/109#-MHADA4x9UD4KdRHSdmJ:-MHADA4x9UD4KdRHSdmK:bbaohqz) ([raw file](https://github.com/kube-hpc/simulator/blob/50ff7029efe6962c8b18d2c6a44242f1a3f83268/src/reducers/diskSpace.reducer.js#L9)):*
> ```
> diskSpace
> ```
should be state (the current state from the method params)

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/109)* status: all files reviewed, 6 unresolved discussions (waiting on @NassiHarel and @reggev)

___
*[src/config/schema/rightSidebar.schema.js, line 36 at r1](https://reviewable.io/reviews/kube-hpc/simulator/109#-MHAQsxVA0VhVBj5-20U:-MHAQsxVA0VhVBj5-20V:b-tlsg25) ([raw file](https://github.com/kube-hpc/simulator/blob/50ff7029efe6962c8b18d2c6a44242f1a3f83268/src/config/schema/rightSidebar.schema.js#L36)):*
> ```JavaScript
>     },
>     {
>       name: RIGHT_SIDEBAR_NAMES.DISK,
> ```

Don't show if disk data is not available? like for GPU below?

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/109)* status: 8 of 18 files reviewed, 6 unresolved discussions (waiting on @reggev and @yehiyam)

___
*[src/components/Sidebar/SidebarRight/Content.react.js, line 62 at r1](https://reviewable.io/reviews/kube-hpc/simulator/109#-MHABXGuByGYB2uPibE6:-MHB3VI4CO15lIsdyM_Z:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/50ff7029efe6962c8b18d2c6a44242f1a3f83268/src/components/Sidebar/SidebarRight/Content.react.js#L62)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

I think `Hkube Storage Usage` is more appropriate
</blockquote></details>

Done.
___
*[src/components/Sidebar/SidebarRight/DiskSpace/DiskSpace.react.js, line 20 at r1](https://reviewable.io/reviews/kube-hpc/simulator/109#-MHACFSt4vs_ox3d6P1l:-MHB3OIN2XTpp47JP7Ce:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/50ff7029efe6962c8b18d2c6a44242f1a3f83268/src/components/Sidebar/SidebarRight/DiskSpace/DiskSpace.react.js#L20)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

I think Dennis put the colors in 'styles/colors'
</blockquote></details>

Done.
___
*[src/components/Sidebar/SidebarRight/DiskSpace/DiskSpace.react.js, line 50 at r1](https://reviewable.io/reviews/kube-hpc/simulator/109#-MHACUr98LvdupVo3PCa:-MHBOebxDoEiPwj2BZMa:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/50ff7029efe6962c8b18d2c6a44242f1a3f83268/src/components/Sidebar/SidebarRight/DiskSpace/DiskSpace.react.js#L50)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Put a red/orange dot on the storage usage icon, like on the CPU and MEM
</blockquote></details>

Done.
___
*[src/components/Sidebar/SidebarRight/DiskSpace/DiskSpace.react.js, line 81 at r1](https://reviewable.io/reviews/kube-hpc/simulator/109#-MHACf3Y4ilTQQPda2FA:-MHBOfuP6X0CDye-eGW7:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/50ff7029efe6962c8b18d2c6a44242f1a3f83268/src/components/Sidebar/SidebarRight/DiskSpace/DiskSpace.react.js#L81)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Same as above. Put all colors in one place
</blockquote></details>

Done.
___
*[src/config/schema/rightSidebar.schema.js, line 36 at r1](https://reviewable.io/reviews/kube-hpc/simulator/109#-MHAQsxVA0VhVBj5-20U:-MHArfjpBXfEzspjiCWH:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/50ff7029efe6962c8b18d2c6a44242f1a3f83268/src/config/schema/rightSidebar.schema.js#L36)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

Don't show if disk data is not available? like for GPU below?
</blockquote></details>

Done.
___
*[src/reducers/diskSpace.reducer.js, line 9 at r1](https://reviewable.io/reviews/kube-hpc/simulator/109#-MHADA4x9UD4KdRHSdmJ:-MHApIhm2WmMke7DwFSL:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/50ff7029efe6962c8b18d2c6a44242f1a3f83268/src/reducers/diskSpace.reducer.js#L9)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

> ```
> diskSpace
> ```
should be state (the current state from the method params)
</blockquote></details>

Done.

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/109)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel and @reggev)

___
*[src/components/Sidebar/SidebarRight/Content.react.js, line 62 at r1](https://reviewable.io/reviews/kube-hpc/simulator/109#-MHABXGuByGYB2uPibE6:-MHBUrqF6aeJi_F2iaQO:b6vd512) ([raw file](https://github.com/kube-hpc/simulator/blob/50ff7029efe6962c8b18d2c6a44242f1a3f83268/src/components/Sidebar/SidebarRight/Content.react.js#L62)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Maybe change to Storage?

**Pull request merged**
