### PR TITLE
feat: drivers table

### PR DESCRIPTION
**Pull request by NassiHarel**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/163)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 5 of 6 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/163)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

___
*[src/index.js, line 1 at r3](https://reviewable.io/reviews/kube-hpc/simulator/163#-Mb5H3Br8Twnsg__EXIY:-Mb5H3Bs36J-8l9fXogh:btxbe0v) ([raw file](https://github.com/kube-hpc/simulator/blob/a044961d70637ea6748a8052732cb3203e50fc44/src/index.js#L1)):*
> ```JavaScript
> import 'core-js/features/array';
> ```

This is here to polyfill Array.(something) for older browsers.

**Review by yehiyam — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/163)* status: all files reviewed, 1 unresolved discussion (waiting on @NassiHarel)

**Review by NassiHarel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/163)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[src/index.js, line 1 at r3](https://reviewable.io/reviews/kube-hpc/simulator/163#-Mb5H3Br8Twnsg__EXIY:-Mb5Tapw4m9Jcq37Sf4D:brcv7f6) ([raw file](https://github.com/kube-hpc/simulator/blob/a044961d70637ea6748a8052732cb3203e50fc44/src/index.js#L1)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

This is here to polyfill Array.(something) for older browsers.
</blockquote></details>

It threw an error, now it works somehow...

**Review by yehiyam — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/163)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @NassiHarel)

**Pull request merged**
