### PR TITLE
Improve wizard

### PR DESCRIPTION
**Pull request by reggev**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/147)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/147)* status: all files reviewed, 1 unresolved discussion (waiting on @reggev)

___
*[src/components/common/Json/JsonEditor/index.js, line 9 at r2](https://reviewable.io/reviews/kube-hpc/simulator/147#-MWdlPsj9YMY345Hj8Dm:-MWdlPsj9YMY345Hj8Dn:b-640uxv) ([raw file](https://github.com/kube-hpc/simulator/blob/919e1658c37ead2913d239a4a365df46b3caf25d/src/components/common/Json/JsonEditor/index.js#L9)):*
> ```JavaScript
>   onChange = () => {},
>   value: controlledValue = '',
>   // height = '60vh',
> ```

delete if not used

**Review by reggev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/147)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[src/components/common/Json/JsonEditor/index.js, line 9 at r2](https://reviewable.io/reviews/kube-hpc/simulator/147#-MWdlPsj9YMY345Hj8Dm:-MWdnHmk2ezzmY4GyPs5:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/919e1658c37ead2913d239a4a365df46b3caf25d/src/components/common/Json/JsonEditor/index.js#L9)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

delete if not used
</blockquote></details>

Done.

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/147#-:-MWdormb21dn71TW9KmV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @reggev)

**Pull request merged**
