### PR TITLE
Datasource external storage

### PR DESCRIPTION
**Pull request by reggev**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/139)

### CODE REVIEW

**Review by yehiyam — APPROVED** [review]
:lgtm:

> Reviewed 6 of 10 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/139#-:-MTBGnW_BXQ6GdZzlWPc:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @reggev)

___
*[.env, line 1 at r2](https://reviewable.io/reviews/kube-hpc/simulator/139#-MTBEWhgEcaYhj6jRXpn:-MTBEWhh-y9iwIVATkdb:bfnmcfe) ([raw file](https://github.com/kube-hpc/simulator/blob/08e2c745066ba5a858657344cc315162b4cc9fa1/.env#L1)):*
> ```Shell
> ESLINT_NO_DEV_ERRORS=true
> ```

don't put .env in git. it should be in gitignore
___
*[.gitignore, line 14 at r2](https://reviewable.io/reviews/kube-hpc/simulator/139#-MTBErVd9mVaZOKu3XGx:-MTBErVd9mVaZOKu3XGy:b-rnsj0q) ([raw file](https://github.com/kube-hpc/simulator/blob/096de71f635274ac85bca690f7aa51b23f3d0c59/.gitignore#L14)):*
> ```ignore
> # misc
> .DS_Store
> .env
> ```

don't!

**Review by reggev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/139)* status: all files reviewed, 2 unresolved discussions (waiting on @reggev and @yehiyam)

___
*[.gitignore, line 14 at r2](https://reviewable.io/reviews/kube-hpc/simulator/139#-MTBErVd9mVaZOKu3XGx:-MTBJz570Bt0juY1NLBI:b8wwsr2) ([raw file](https://github.com/kube-hpc/simulator/blob/096de71f635274ac85bca690f7aa51b23f3d0c59/.gitignore#L14)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

don't!
</blockquote></details>

create-react-app supports both .env and .env.local
some configurations(not keys) are set on .env, and keys/private values are saved on .local files

**Review by yehiyam — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/139)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @reggev)

**Review by yehiyam — APPROVED** [review]
> Reviewed 8 of 12 files at r3, 12 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/139)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
