### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by reggev**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/143)

### CODE REVIEW

**Review by yehiyam — APPROVED** [review]
> Reviewed 15 of 16 files at r1, 44 of 53 files at r2, 1 of 1 files at r3, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/143)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by yehiyam — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/143)* status: all files reviewed, 1 unresolved discussion (waiting on @reggev)

___
*[src/components/common/Json/JsonTable/JsonTable.react.js, line 33 at r4](https://reviewable.io/reviews/kube-hpc/simulator/143#-MUISl29BXeHM71AYd63:-MUISl29BXeHM71AYd64:blh3awg) ([raw file](https://github.com/kube-hpc/simulator/blob/81f5362f0f622a7290e74bd612789891f579756a/src/components/common/Json/JsonTable/JsonTable.react.js#L33)):*
> ```JavaScript
> }) => {
>   const [downloadHref, setDownloadHref] = useState(null);
>   const handleDownload = useCallback(
> ```

something is not working with the download link

**Review by yehiyam — COMMENTED** [review]
> Reviewed 56 of 68 files at r5, 2 of 4 files at r6, 7 of 7 files at r8, 11 of 11 files at r10, 1 of 1 files at r11, 3 of 3 files at r12, 3 of 3 files at r13.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/143)* status: all files reviewed, 2 unresolved discussions (waiting on @reggev)

___
*[src/config/template/addPipeline.template.js, line 7 at r12](https://reviewable.io/reviews/kube-hpc/simulator/143#-MVMwhsL69poFco297cd:-MVMwhsL69poFco297ce:b-8tuibk) ([raw file](https://github.com/kube-hpc/simulator/blob/99bbbcbef2d756f341f32045ce596e5231fccdaf/src/config/template/addPipeline.template.js#L7)):*
> ```JavaScript
>     {
>       kind: 'algorithm',
>       nodeName: 'node-0',
> ```

This is not a valid node name
___
*[src/Routes/SidebarRight/AddPipeline/test.json, line 1 at r13](https://reviewable.io/reviews/kube-hpc/simulator/143#-MVPuuPuAAq-6Q6JQx04:-MVPuuPuAAq-6Q6JQx05:bzghclr) ([raw file](https://github.com/kube-hpc/simulator/blob/6329aae9fc4dccc7f6af5f4d46302114f718e2d8/src/Routes/SidebarRight/AddPipeline/test.json#L1)):*
> ```JSON
> {
> ```

is this file used?

**Review by reggev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/143)* status: 126 of 134 files reviewed, 2 unresolved discussions (waiting on @yehiyam)

___
*[src/config/template/addPipeline.template.js, line 7 at r12](https://reviewable.io/reviews/kube-hpc/simulator/143#-MVMwhsL69poFco297cd:-MVR_GNb0vMoMPKsFhGB:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/99bbbcbef2d756f341f32045ce596e5231fccdaf/src/config/template/addPipeline.template.js#L7)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

This is not a valid node name
</blockquote></details>

Done.
___
*[src/Routes/SidebarRight/AddPipeline/test.json, line 1 at r13](https://reviewable.io/reviews/kube-hpc/simulator/143#-MVPuuPuAAq-6Q6JQx04:-MVR_FUJ74JQaN-gvFhz:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/6329aae9fc4dccc7f6af5f4d46302114f718e2d8/src/Routes/SidebarRight/AddPipeline/test.json#L1)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

is this file used?
</blockquote></details>

Done.

**Review by reggev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/143)* status: 133 of 135 files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[src/Routes/SidebarRight/AddDataSource/index.js, line 61 at r15](https://reviewable.io/reviews/kube-hpc/simulator/143#-MVRakCmDej10azxMVAx:-MVRcTKY8Zwz6_oDniqx:b-69dptf) ([raw file](https://github.com/kube-hpc/simulator/blob/478de6b285d40fb84915e125244324568a2d03d7/src/Routes/SidebarRight/AddDataSource/index.js#L61)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

shouldn't this be endpointUrl?
</blockquote></details>

it should be repository url, I fixed that now

**Pull request merged**
