### PR TITLE
re-structured reducer

### PR DESCRIPTION
**Pull request by reggev**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/154)

### CODE REVIEW

**Review by yehiyam — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/154)* status: all files reviewed, 1 unresolved discussion (waiting on @reggev)

___
*[src/Routes/Tables/Workers/index.js, line 19 at r1](https://reviewable.io/reviews/kube-hpc/simulator/154#-MXlOgvu399s_53TsFno:-MXlOgvv2SVvSTrWOZHw:bg6gc86) ([raw file](https://github.com/kube-hpc/simulator/blob/cbde659583426259c981aed0bddbc37b812ea6c8/src/Routes/Tables/Workers/index.js#L19)):*
> ```JavaScript
> 
> const ExpandedRow = collection => record => {
>   const entries = collection[record?.algorithmName] || [];
> ```

if record is null/undefined you will get `collection[undefined]`. Is that what you meant?

**Review by reggev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/154)* status: all files reviewed, 1 unresolved discussion (waiting on @yehiyam)

___
*[src/Routes/Tables/Workers/index.js, line 19 at r1](https://reviewable.io/reviews/kube-hpc/simulator/154#-MXlOgvu399s_53TsFno:-MXlPKxF49h91J-UB926:b-g3virs) ([raw file](https://github.com/kube-hpc/simulator/blob/cbde659583426259c981aed0bddbc37b812ea6c8/src/Routes/Tables/Workers/index.js#L19)):*
<details><summary><i>Previously, yehiyam wrote…</i></summary><blockquote>

if record is null/undefined you will get `collection[undefined]`. Is that what you meant?
</blockquote></details>

yes, it will fallback to []

**Review by yehiyam — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/154)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @reggev)

**Review by yehiyam — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/154)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @reggev)

**Pull request merged**
