### PR TITLE
Marge UI v3 and preferred v1

### PR DESCRIPTION
**Pull request by zivglik**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/195)

### CODE REVIEW

**Comment by maty21** [comment]
___
*[src/Routes/Tables/Drivers/index.js, line 17 at r7](https://reviewable.io/reviews/kube-hpc/simulator/195#-Mz9KLTd0uGOfY7jMCT_:-Mz9KLTd0uGOfY7jMCTa:bjsbjzi) ([raw file](https://github.com/kube-hpc/simulator/blob/4f6d346f5b3673457e25d8d1e14a882ee708f461/src/Routes/Tables/Drivers/index.js#L17)):*
> ```JavaScript
>   const { driverId, podName } = record;
>   const driver = collection.find(c => c.driverId === driverId);
>   const jobs =
> ```

move to function ?

**Comment by maty21** [comment]
___
*[src/Routes/Tables/Jobs/GraphTab/index.js, line 101 at r7](https://reviewable.io/reviews/kube-hpc/simulator/195#-Mz9KgOBAuwU0aMlDMfW:-Mz9KgOBAuwU0aMlDMfX:b-hulx69) ([raw file](https://github.com/kube-hpc/simulator/blob/4f6d346f5b3673457e25d8d1e14a882ee708f461/src/Routes/Tables/Jobs/GraphTab/index.js#L101)):*
> ```JavaScript
>       res = true;
>     } else if (
>       node != null &&
> ```

to complicated could be a bug-prone  try to think on a simple expression

**Comment by maty21** [comment]
___
*[src/Routes/Tables/QueueOrderJobs/useQueueOrderJobs.js, line 190 at r8](https://reviewable.io/reviews/kube-hpc/simulator/195#-Mz9d-CQEMBoWzma8IlH:-Mz9d-CQEMBoWzma8IlI:bky9uce) ([raw file](https://github.com/kube-hpc/simulator/blob/70784349525196abd6bd1d372623418221045b11/src/Routes/Tables/QueueOrderJobs/useQueueOrderJobs.js#L190)):*
> ```JavaScript
>   const type = typeFilter.toString().toLowerCase();
>   let res = [];
>   try {
> ```

move it to  function u using the same logic in to different places on the same component  
consider to change the elseif to a Factoty something like this 

const types  ={
 TypeFilter.PIPELINE: getManagedByPipeline

}

usage :
await types[type]()

**Comment by maty21** [comment]
___
*[src/Routes/Tables/QueueOrderJobs/OrderComponents.js, line 1 at r8](https://reviewable.io/reviews/kube-hpc/simulator/195#-Mz9eBxKAB8F6cFSRhGq:-Mz9eBxKAB8F6cFSRhGr:b-60ogy6) ([raw file](https://github.com/kube-hpc/simulator/blob/70784349525196abd6bd1d372623418221045b11/src/Routes/Tables/QueueOrderJobs/OrderComponents.js#L1)):*
> ```JavaScript
> import React, { forwardRef } from 'react';
> ```

why the name is not the same as the file name also if its queue Order  than add queue to the name

**Review by maty21 — CHANGES_REQUESTED** [review]
> Reviewed 19 of 35 files at r1, 1 of 8 files at r4, 4 of 12 files at r5, 4 of 4 files at r6, 11 of 11 files at r7.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/195)* status: 37 of 40 files reviewed, 10 unresolved discussions (waiting on @maty21 and @zivglik)

___
*[package.json, line 37 at r7](https://reviewable.io/reviews/kube-hpc/simulator/195#-Mz9JmjE8qo-3M6lRl-7:-Mz9JmjE8qo-3M6lRl-8:bmd1fch) ([raw file](https://github.com/kube-hpc/simulator/blob/4f6d346f5b3673457e25d8d1e14a882ee708f461/package.json#L37)):*
> ```JSON
>   "dependencies": {
>     "@ant-design/icons": "^4.6.2",
>     "array-move": "^4.0.0",
> ```

maybe move to dev dep
___
*[src/Routes/Tables/QueueOrderJobs/QCount.js, line 1 at r7](https://reviewable.io/reviews/kube-hpc/simulator/195#-Mz9bs_f4xDicyz5pFqk:-Mz9bs_f4xDicyz5pFql:b-l1cqfb) ([raw file](https://github.com/kube-hpc/simulator/blob/4f6d346f5b3673457e25d8d1e14a882ee708f461/src/Routes/Tables/QueueOrderJobs/QCount.js#L1)):*
> ```JavaScript
> import React from 'react';
> ```

change component name to query count
___
*[src/Routes/Tables/QueueOrderJobs/index.js, line 18 at r7](https://reviewable.io/reviews/kube-hpc/simulator/195#-Mz9L0KV0-80hPmAArZA:-Mz9L0KV0-80hPmAArZB:bsxvmpi) ([raw file](https://github.com/kube-hpc/simulator/blob/4f6d346f5b3673457e25d8d1e14a882ee708f461/src/Routes/Tables/QueueOrderJobs/index.js#L18)):*
> ```JavaScript
> const PAGE_SIZE_TABLE = 50;
> 
> class QueueOrderJobs extends React.Component {
> ```

why use classical implementation?
___
*[src/Routes/Tables/QueueOrderJobs/TableOrderConsolidated.js, line 10 at r8](https://reviewable.io/reviews/kube-hpc/simulator/195#-Mz9cE-I5c6EUPUsWf1A:-Mz9cE-J5aivvmRAQOrp:b-20l6x) ([raw file](https://github.com/kube-hpc/simulator/blob/70784349525196abd6bd1d372623418221045b11/src/Routes/Tables/QueueOrderJobs/TableOrderConsolidated.js#L10)):*
> ```JavaScript
> 
> const scrollElement = '.TableAllInOne div.ant-table-body';
> class TableOrderConsolidated extends React.Component {
> ```

why class implementation
___
*[src/Routes/Tables/QueueOrderJobs/TablePreferred.js, line 17 at r8](https://reviewable.io/reviews/kube-hpc/simulator/195#-Mz9cJiA-5uJDUaglg10:-Mz9cJiA-5uJDUaglg11:b-7tdlyt) ([raw file](https://github.com/kube-hpc/simulator/blob/70784349525196abd6bd1d372623418221045b11/src/Routes/Tables/QueueOrderJobs/TablePreferred.js#L17)):*
> ```JavaScript
> } from './OrderComponents';
> 
> class TablePreferred extends React.Component {
> ```

agian
___
*[src/Routes/Tables/QueueOrderJobs/TablePreferred.js, line 136 at r8](https://reviewable.io/reviews/kube-hpc/simulator/195#-Mz9cNvH9gBh0evX6uJf:-Mz9cNvH9gBh0evX6uJg:buo4f16) ([raw file](https://github.com/kube-hpc/simulator/blob/70784349525196abd6bd1d372623418221045b11/src/Routes/Tables/QueueOrderJobs/TablePreferred.js#L136)):*
> ```JavaScript
> 
>               // light border tr where the input element
>               if (isDrag) {
> ```

move this implementation to function ?

**Review by zivglik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/195)* status: 29 of 55 files reviewed, 10 unresolved discussions (waiting on @maty21)

___
*[package.json, line 37 at r7](https://reviewable.io/reviews/kube-hpc/simulator/195#-Mz9JmjE8qo-3M6lRl-7:-MzANiJa3pRkgUrXtYw3:b-2wqrnz) ([raw file](https://github.com/kube-hpc/simulator/blob/4f6d346f5b3673457e25d8d1e14a882ee708f461/package.json#L37)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

maybe move to dev dep
</blockquote></details>

i uninstall this we not need this



_Code quote:_
```JSON
"array-move": "^4.0.0"
```
___
*[src/Routes/Tables/Drivers/index.js, line 17 at r7](https://reviewable.io/reviews/kube-hpc/simulator/195#-Mz9KLTd0uGOfY7jMCT_:-Mz9ezT_9I-03m5EpuTc:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/4f6d346f5b3673457e25d8d1e14a882ee708f461/src/Routes/Tables/Drivers/index.js#L17)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

move to function ? 
</blockquote></details>

Done.
___
*[src/Routes/Tables/Jobs/GraphTab/index.js, line 101 at r7](https://reviewable.io/reviews/kube-hpc/simulator/195#-Mz9KgOBAuwU0aMlDMfW:-Mz9f4e2CLs7cybyfPPX:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/4f6d346f5b3673457e25d8d1e14a882ee708f461/src/Routes/Tables/Jobs/GraphTab/index.js#L101)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

to complicated could be a bug-prone  try to think on a simple expression
</blockquote></details>

Done.
___
*[src/Routes/Tables/QueueOrderJobs/index.js, line 18 at r7](https://reviewable.io/reviews/kube-hpc/simulator/195#-Mz9L0KV0-80hPmAArZA:-Mz9gGlt2dG9d8_yC4ra:b-bx09gu) ([raw file](https://github.com/kube-hpc/simulator/blob/4f6d346f5b3673457e25d8d1e14a882ee708f461/src/Routes/Tables/QueueOrderJobs/index.js#L18)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

why use classical implementation?
</blockquote></details>

At the time I did an example of QUEUE that I tested on DRAG & DROP
Finally I finished I tried to convert the example to HOOKS
And I had problems with it, so you told me to leave it at that

I can try to convert it again but it will take me a while
___
*[src/Routes/Tables/QueueOrderJobs/OrderComponents.js, line 1 at r8](https://reviewable.io/reviews/kube-hpc/simulator/195#-Mz9eBxKAB8F6cFSRhGq:-Mz9iJVfCZsmm79p_05J:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/70784349525196abd6bd1d372623418221045b11/src/Routes/Tables/QueueOrderJobs/OrderComponents.js#L1)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

why the name is not the same as the file name also if its queue Order  than add queue to the name
</blockquote></details>

Done.
___
*[src/Routes/Tables/QueueOrderJobs/QCount.js, line 1 at r7](https://reviewable.io/reviews/kube-hpc/simulator/195#-Mz9bs_f4xDicyz5pFqk:-Mz9ip1H8smGE101Ls1w:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/4f6d346f5b3673457e25d8d1e14a882ee708f461/src/Routes/Tables/QueueOrderJobs/QCount.js#L1)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

change component name to query count
</blockquote></details>

Done.
___
*[src/Routes/Tables/QueueOrderJobs/TableOrderConsolidated.js, line 10 at r8](https://reviewable.io/reviews/kube-hpc/simulator/195#-Mz9cE-I5c6EUPUsWf1A:-MzEKNzr22_qzvVnJno8:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/70784349525196abd6bd1d372623418221045b11/src/Routes/Tables/QueueOrderJobs/TableOrderConsolidated.js#L10)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

why class implementation
</blockquote></details>

Done.
___
*[src/Routes/Tables/QueueOrderJobs/TablePreferred.js, line 17 at r8](https://reviewable.io/reviews/kube-hpc/simulator/195#-Mz9cJiA-5uJDUaglg10:-MzAOJNl0Z-u3fGOmCco:b-e9nvm0) ([raw file](https://github.com/kube-hpc/simulator/blob/70784349525196abd6bd1d372623418221045b11/src/Routes/Tables/QueueOrderJobs/TablePreferred.js#L17)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

agian
</blockquote></details>

At the time I did an example of QUEUE that I tested on DRAG & DROP
Finally I finished I tried to convert the example to HOOKS
And I had problems with it, so you told me to leave it at that

I can try to convert it again but it will take me a while
___
*[src/Routes/Tables/QueueOrderJobs/TablePreferred.js, line 136 at r8](https://reviewable.io/reviews/kube-hpc/simulator/195#-Mz9cNvH9gBh0evX6uJf:-Mz9nIre-vhblaY3Agq1:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/70784349525196abd6bd1d372623418221045b11/src/Routes/Tables/QueueOrderJobs/TablePreferred.js#L136)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

move this implementation to function ? 
</blockquote></details>

Done.
___
*[src/Routes/Tables/QueueOrderJobs/useQueueOrderJobs.js, line 190 at r8](https://reviewable.io/reviews/kube-hpc/simulator/195#-Mz9d-CQEMBoWzma8IlH:-MzEKYb2EiPo94Bv3oEy:ba39iwb) ([raw file](https://github.com/kube-hpc/simulator/blob/70784349525196abd6bd1d372623418221045b11/src/Routes/Tables/QueueOrderJobs/useQueueOrderJobs.js#L190)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

move it to  function u using the same logic in to different places on the same component  
consider to change the elseif to a Factoty something like this 

const types  ={
 TypeFilter.PIPELINE: getManagedByPipeline

}

usage :
await types[type]()
</blockquote></details>

I could not think of anything else effective

**Comment by maty21** [comment]
___
*[package.json, line 39 at r9](https://reviewable.io/reviews/kube-hpc/simulator/195#-MzEeP4z9MwjZkRhdPDT:-MzEeP4z9MwjZkRhdPDU:b-8n2arg) ([raw file](https://github.com/kube-hpc/simulator/blob/e4a05d7ab113679e06810e5c15ca3d6afb085fc5/package.json#L39)):*
> ```JSON
>     "dotenv": "^8.2.0",
>     "express": "^4.17.1",
>     "react-sortable-hoc": "^2.0.0"
> ```

move this as well

**Review by maty21 — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/195)* status: all files reviewed, 2 unresolved discussions (waiting on @zivglik)

___
*[src/Routes/Tables/QueueOrderJobs/QueueOrderComponents_old.js, line 32 at r9](https://reviewable.io/reviews/kube-hpc/simulator/195#-MzEe5CX80GVgxMUjRYP:-MzEe5CX80GVgxMUjRYQ:b2d4o9l) ([raw file](https://github.com/kube-hpc/simulator/blob/e4a05d7ab113679e06810e5c15ca3d6afb085fc5/src/Routes/Tables/QueueOrderJobs/QueueOrderComponents_old.js#L32)):*
> ```JavaScript
>   <JobTime startTime={startTime} results={results} />
> );
> export const TypeRow = type =>
> ```

remove this file

**Review by zivglik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/195)* status: all files reviewed, 2 unresolved discussions (waiting on @maty21)

___
*[package.json, line 39 at r9](https://reviewable.io/reviews/kube-hpc/simulator/195#-MzEeP4z9MwjZkRhdPDT:-MzEtGxd1stWBTFF0zGr:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/e4a05d7ab113679e06810e5c15ca3d6afb085fc5/package.json#L39)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

move this as well
</blockquote></details>

Done.



_Code quote:_
```JSON
react-sortable-hoc
```
___
*[src/Routes/Tables/QueueOrderJobs/QueueOrderComponents_old.js, line 32 at r9](https://reviewable.io/reviews/kube-hpc/simulator/195#-MzEe5CX80GVgxMUjRYP:-MzEtJNB8az0EegLSAMo:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/e4a05d7ab113679e06810e5c15ca3d6afb085fc5/src/Routes/Tables/QueueOrderJobs/QueueOrderComponents_old.js#L32)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

remove this file 
</blockquote></details>

Done.

**Review by maty21 — COMMENTED** [review]
> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/195)* status: all files reviewed, 1 unresolved discussion (waiting on @maty21)

**Review by maty21 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/195)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zivglik)

**Pull request merged**
