### PR TITLE
fix ui 

### PR DESCRIPTION
**Pull request by zivglik**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/175)

### CODE REVIEW

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/175#-:-MfgRirADOJvlO3djCqH:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @zivglik)

___
*[src/Routes/SidebarRight/AddPipeline/index.js, line 112 at r3](https://reviewable.io/reviews/kube-hpc/simulator/175#-MfgQnZZ-GpAyvXIkkEf:-MfgQnZZ-GpAyvXIkkEg:b8vl4v0) ([raw file](https://github.com/kube-hpc/simulator/blob/9c3a3e0442e45ce90ee325fc35cd50d8cc670c0f/src/Routes/SidebarRight/AddPipeline/index.js#L112)):*
> ```
> // addPipeline(
> ```

Try not to leave comments in code...

**Comment by maty21** [comment]
___
*[src/Routes/SidebarRight/AddPipeline/index.js, line 90 at r6](https://reviewable.io/reviews/kube-hpc/simulator/175#-MgF_VvSA3NmOCP6NKHn:-MgF_VvSA3NmOCP6NKHo:b-qlhmht) ([raw file](https://github.com/kube-hpc/simulator/blob/6ce3fdc74f78e83da23ff30b784594d06503f415/src/Routes/SidebarRight/AddPipeline/index.js#L90)):*
> ```JavaScript
>     async data => {
>       try {
>         const res = await client.post('store/pipelines', { ...data });
> ```

move to a different file in the hooks folder check if there's already a hook for storing pipleine

**Comment by maty21** [comment]
___
*[src/Routes/SidebarRight/AddPipeline/index.js, line 117 at r6](https://reviewable.io/reviews/kube-hpc/simulator/175#-MgFbOY570BSxI2Y6tJw:-MgFbOY570BSxI2Y6tJx:b-albs8b) ([raw file](https://github.com/kube-hpc/simulator/blob/6ce3fdc74f78e83da23ff30b784594d06503f415/src/Routes/SidebarRight/AddPipeline/index.js#L117)):*
> ```JavaScript
>   );
> 
>   const wizardClear = useCallback(() => {
> ```

see if it make sense to move it

**Comment by maty21** [comment]
___
*[src/Routes/SidebarRight/AddPipeline/index.js, line 117 at r6](https://reviewable.io/reviews/kube-hpc/simulator/175#-MgFbOY570BSxI2Y6tJw:-MgFcPiM5JIaEWnbUlbs:b4es23z) ([raw file](https://github.com/kube-hpc/simulator/blob/6ce3fdc74f78e83da23ff30b784594d06503f415/src/Routes/SidebarRight/AddPipeline/index.js#L117)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

see if it make sense to move it
</blockquote></details>

see if it make sense to  remove useCallback  if it not mandatory

**Comment by maty21** [comment]
___
*[src/Routes/SidebarRight/AddPipeline/Wizard.js, line 150 at r6](https://reviewable.io/reviews/kube-hpc/simulator/175#-MgFhZUM6eqwkRf6x481:-MgFhZUM6eqwkRf6x482:b3ol9t7) ([raw file](https://github.com/kube-hpc/simulator/blob/6ce3fdc74f78e83da23ff30b784594d06503f415/src/Routes/SidebarRight/AddPipeline/Wizard.js#L150)):*
> ```JavaScript
>       const { nodes } = getFieldsValue();
> 
>       for (let ii = 0; ii < nodes.length; ii++) {
> ```

try use setState instead of updating the HTML tags 


try to use foreach if its possible instead of for

**Comment by maty21** [comment]
___
*[src/Routes/SidebarRight/AddPipeline/Steps/Nodes/index.js, line 67 at r6](https://reviewable.io/reviews/kube-hpc/simulator/175#-MgFkNML-5TCoKSiwDjy:-MgFkNML-5TCoKSiwDjz:b-vhaeuh) ([raw file](https://github.com/kube-hpc/simulator/blob/6ce3fdc74f78e83da23ff30b784594d06503f415/src/Routes/SidebarRight/AddPipeline/Steps/Nodes/index.js#L67)):*
> ```JavaScript
>   font-weight: 500;
>   background-color: ${props =>
>     props.tagColor === 'gateway'
> ```

use app color scheme if possible

**Comment by maty21** [comment]
___
*[src/Routes/SidebarRight/AddPipeline/Steps/Nodes/index.js, line 105 at r6](https://reviewable.io/reviews/kube-hpc/simulator/175#-MgFl_rx1agXZGGBg8xK:-MgFl_ry7awUl3unJbBJ:bz6ib6b) ([raw file](https://github.com/kube-hpc/simulator/blob/6ce3fdc74f78e83da23ff30b784594d06503f415/src/Routes/SidebarRight/AddPipeline/Steps/Nodes/index.js#L105)):*
> ```
> useCallback
> ```
remove usecallBack

**Review by zivglik — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/175)* status: 1 of 23 files reviewed, 6 unresolved discussions (waiting on @maty21 and @NassiHarel)

___
*[src/Routes/SidebarRight/AddPipeline/index.js, line 112 at r3](https://reviewable.io/reviews/kube-hpc/simulator/175#-MfgQnZZ-GpAyvXIkkEf:-MgGkYv01efaGmOMXXNA:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/9c3a3e0442e45ce90ee325fc35cd50d8cc670c0f/src/Routes/SidebarRight/AddPipeline/index.js#L112)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> // addPipeline(
> ```

Try not to leave comments in code...
</blockquote></details>

Done.
___
*[src/Routes/SidebarRight/AddPipeline/index.js, line 90 at r6](https://reviewable.io/reviews/kube-hpc/simulator/175#-MgF_VvSA3NmOCP6NKHn:-MgGkZgvD5sGP3MOTFls:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/6ce3fdc74f78e83da23ff30b784594d06503f415/src/Routes/SidebarRight/AddPipeline/index.js#L90)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

move to a different file in the hooks folder check if there's already a hook for storing pipleine
</blockquote></details>

Done.
___
*[src/Routes/SidebarRight/AddPipeline/index.js, line 117 at r6](https://reviewable.io/reviews/kube-hpc/simulator/175#-MgFbOY570BSxI2Y6tJw:-MgGlGsP9neAN6YHmVdA:bp08cg6) ([raw file](https://github.com/kube-hpc/simulator/blob/6ce3fdc74f78e83da23ff30b784594d06503f415/src/Routes/SidebarRight/AddPipeline/index.js#L117)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

see if it make sense to  remove useCallback  if it not mandatory
</blockquote></details>

I have to leave it like this because I send it as a parameter to a button that is in another component
___
*[src/Routes/SidebarRight/AddPipeline/Wizard.js, line 150 at r6](https://reviewable.io/reviews/kube-hpc/simulator/175#-MgFhZUM6eqwkRf6x481:-MgH3cfX6UywTyEESpvI:b-mp65vw) ([raw file](https://github.com/kube-hpc/simulator/blob/6ce3fdc74f78e83da23ff30b784594d06503f415/src/Routes/SidebarRight/AddPipeline/Wizard.js#L150)):*
> try use setState instead of updating the HTML tags
I could not make the loop through the state
The component does not appear to rely on the state
Even having a UI change the state does not change something a little strange there

After all, the state is going through the variables

   initialState,
   setEditorState,

But initialState does not seem to be worth the changes

You can look at it together maybe I missed something

> try to use foreach if its possible instead of for (DONE)
___
*[src/Routes/SidebarRight/AddPipeline/Steps/Nodes/index.js, line 67 at r6](https://reviewable.io/reviews/kube-hpc/simulator/175#-MgFkNML-5TCoKSiwDjy:-MgGvCAy3MCBUsNHcik0:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/6ce3fdc74f78e83da23ff30b784594d06503f415/src/Routes/SidebarRight/AddPipeline/Steps/Nodes/index.js#L67)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

use app color scheme if possible
</blockquote></details>

Done.
___
*[src/Routes/SidebarRight/AddPipeline/Steps/Nodes/index.js, line 105 at r6](https://reviewable.io/reviews/kube-hpc/simulator/175#-MgFl_rx1agXZGGBg8xK:-MgGvJ3gBwwkN9pov7X5:b-896fix) ([raw file](https://github.com/kube-hpc/simulator/blob/6ce3fdc74f78e83da23ff30b784594d06503f415/src/Routes/SidebarRight/AddPipeline/Steps/Nodes/index.js#L105)):*
<details><summary><i>Previously, maty21 (Cube) wrote…</i></summary><blockquote>

> ```
> useCallback
> ```
remove usecallBack 
</blockquote></details>

Done.

**Review by maty21 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, 7 of 8 files at r4, 12 of 14 files at r5, 3 of 3 files at r6, 5 of 6 files at r7, 2 of 2 files at r8, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/simulator/175)* status: all files reviewed, 3 unresolved discussions (waiting on @NassiHarel and @zivglik)

___
*[src/Routes/SidebarRight/AddPipeline/index.js, line 118 at r6](https://reviewable.io/reviews/kube-hpc/simulator/175#-MgFcBAi4aItvxGRMh59:-MgFcBAi4aItvxGRMh5A:b-ovps2r) ([raw file](https://github.com/kube-hpc/simulator/blob/6ce3fdc74f78e83da23ff30b784594d06503f415/src/Routes/SidebarRight/AddPipeline/index.js#L118)):*
> ```
> useCallback
> ```
___
*[.env, line 3 at r6](https://reviewable.io/reviews/kube-hpc/simulator/175#-MgFp0Tk1JfQDP0ula4P:-MgFp0Tk1JfQDP0ula4Q:b-l6mwxj) ([raw file](https://github.com/kube-hpc/simulator/blob/6ce3fdc74f78e83da23ff30b784594d06503f415/.env#L3)):*
> ```Shell
> ESLINT_NO_DEV_ERRORS=true
> TSC_COMPILE_ON_ERROR=true
> MONITOR_BACKEND_USE_LOCATION=false
> ```

remove

**Review by maty21 — APPROVED** [review]

**Pull request merged**
